import type { Package } from '@/types';

// Listing-page projection of STATIC_GLOBAL_PACKAGES: same identity and card
// fields, with itinerary/overview/inclusions stripped so the client bundle does
// not carry every day-by-day. Regenerate whenever a package is added or renamed.

const included = {
  accommodation: false,
  meals: false,
  transfers: false,
  guides: false,
  flights: false,
  activities: false,
};

export const STATIC_GLOBAL_PACKAGE_SUMMARIES: Package[] = [
  {
    id: 'static-global-thailand-pattaya',
    title: 'Pattaya beach break',
    slug: 'pattaya-thailand-3-nights',
    market: 'global',
    category: 'Beach',
    tagline: 'A short Thailand escape with island waters, cabaret lights, and tropical gardens.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '4 days / 3 nights',
    groupSize: 'Private groups from 4 travelers',
    priceInr: 56400,
    priceUsd: 680,
    destinations: ['Bangkok', 'Pattaya', 'Coral Island', 'Nong Nooch'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Easy beach holiday',
    locationIdea: 'Pattaya, Thailand',
    status: 'published',
    createdAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'static-global-vietnam-danang-ho-chi-minh',
    title: 'Da Nang to Ho Chi Minh discovery',
    slug: 'vietnam-da-nang-ho-chi-minh-6-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'Golden Bridge, Hoi An lanterns, Saigon landmarks, and the Cu Chi tunnel network.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '7 days / 6 nights',
    groupSize: 'Private tour for couples, families, and small groups',
    priceInr: null,
    priceUsd: 915,
    destinations: ['Da Nang', 'Ba Na Hills', 'Hoi An', 'Ho Chi Minh City', 'Cu Chi'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Culture, coast, and city',
    locationIdea: 'Central and southern Vietnam',
    status: 'published',
    createdAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'static-global-vietnam-phu-quoc-hanoi-halong',
    title: 'Phu Quoc, Hanoi and Halong Bay',
    slug: 'vietnam-phu-quoc-hanoi-halong-7-nights',
    market: 'global',
    category: 'Beach',
    tagline: 'Island snorkeling, Hanoi old quarter, Halong Bay cruising, and Ninh Binh limestone landscapes.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '8 days / 7 nights',
    groupSize: 'Private and small-group touring blend',
    priceInr: null,
    priceUsd: 650,
    destinations: ['Phu Quoc', 'Hanoi', 'Halong Bay', 'Ninh Binh', 'Trang An'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Island to limestone landscapes',
    locationIdea: 'Southern island and northern Vietnam',
    status: 'published',
    createdAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'static-global-kenya-safari',
    title: 'Kenya safari circuit',
    slug: 'kenya-amboseli-naivasha-masai-mara-9-nights',
    market: 'global',
    category: 'Safari',
    tagline: 'Amboseli elephants, Lake Naivasha, Hell\'s Gate, and extended Masai Mara game drives.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '10 days / 9 nights',
    groupSize: 'Private safari quote for small groups',
    priceInr: null,
    priceUsd: 5387,
    destinations: ['Nairobi', 'Amboseli', 'Lake Naivasha', 'Hell\'s Gate', 'Masai Mara'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Wildlife-forward safari',
    locationIdea: 'Amboseli, Naivasha, and Masai Mara',
    status: 'published',
    createdAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'static-global-switzerland-paris',
    title: 'Switzerland and Paris',
    slug: 'switzerland-paris-7-nights',
    market: 'global',
    category: 'Adventure',
    tagline: 'Alpine summits, Rhine Falls, and Paris landmarks on one flight-inclusive route.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '8 days / 7 nights',
    groupSize: 'Small group departures and private quotes',
    priceInr: null,
    priceUsd: 2450,
    destinations: ['Zurich', 'Rhine Falls', 'Black Forest', 'Mt Titlis', 'Lucerne', 'Interlaken', 'Paris'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Alps and city in one route',
    locationIdea: 'Central Switzerland and Paris',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-spain-grand-tour',
    title: 'Spain from Madrid to Barcelona',
    slug: 'spain-madrid-andalusia-barcelona-8-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'Toledo, the Mezquita, the Alhambra, and the Mediterranean coast on one overland route.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '9 days / 8 nights',
    groupSize: 'Fixed departures and private group quotes',
    priceInr: null,
    priceUsd: 2940,
    destinations: ['Madrid', 'Toledo', 'Cordoba', 'Seville', 'Granada', 'Guadix', 'Valencia', 'Barcelona'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Overland heritage route',
    locationIdea: 'Central Spain, Andalusia, and Catalonia',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-japan-tokyo-hiroshima-kyoto',
    title: 'Japan from Tokyo to Kyoto via the Inland Sea',
    slug: 'japan-tokyo-hiroshima-kyoto-7-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'Tokyo, Hiroshima and Miyajima, Shikoku onsen towns, Mount Koya, and Kyoto.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '8 days / 7 nights',
    groupSize: 'Private tour for couples, families, and small groups',
    priceInr: null,
    priceUsd: 4165,
    destinations: ['Tokyo', 'Hiroshima', 'Miyajima', 'Matsuyama', 'Kobe', 'Mount Koya', 'Kyoto'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Temples, onsen, and the Inland Sea',
    locationIdea: 'Honshu, Shikoku, and Mount Koya',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-japan-tokyo-fuji-kyoto',
    title: 'Japan short break with Mount Fuji',
    slug: 'japan-tokyo-fuji-kyoto-5-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'Tokyo, a ryokan night at Lake Kawaguchi under Fuji, and two days in Kyoto.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '6 days / 5 nights',
    groupSize: 'Private tour for couples, families, and small groups',
    priceInr: null,
    priceUsd: 3050,
    destinations: ['Tokyo', 'Lake Kawaguchi', 'Mount Fuji', 'Kyoto', 'Arashiyama'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Compact first-time Japan',
    locationIdea: 'Tokyo, Fuji Five Lakes, and Kyoto',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-japan-grand-tour',
    title: 'Japan grand tour',
    slug: 'japan-grand-tour-10-nights',
    market: 'global',
    category: 'Spiritual',
    tagline: 'Mount Koya monasteries, Nikko shrines, Nagano snow monkeys, and the Inland Sea.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1503640538573-148065ba4904?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '11 days / 10 nights',
    groupSize: 'Private tour for small groups',
    priceInr: null,
    priceUsd: 5065,
    destinations: ['Tokyo', 'Hiroshima', 'Matsuyama', 'Kobe', 'Mount Koya', 'Kyoto', 'Nagano', 'Ikaho', 'Nikko'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Temples, shrines, and mountain towns',
    locationIdea: 'Honshu, Shikoku, and the Japan Alps',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-central-europe-budapest-vienna-prague',
    title: 'Budapest, Vienna and Prague',
    slug: 'central-europe-budapest-vienna-prague-6-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'Three Habsburg capitals, two nights each, linked by coach along the Danube.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1592906209472-a36b1f3782ef?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '7 days / 6 nights',
    groupSize: 'Small group departures and private quotes',
    priceInr: null,
    priceUsd: 2913,
    destinations: ['Budapest', 'Vienna', 'Prague'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Imperial capitals by coach',
    locationIdea: 'Hungary, Austria, and Czechia',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-vietnam-hanoi-halong-short',
    title: 'Hanoi and Halong Bay short break',
    slug: 'vietnam-hanoi-halong-4-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'Old Quarter streets, a water puppet show, and a night aboard a Halong Bay cruise.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1509030450996-dd1a26dda07a?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '5 days / 4 nights',
    groupSize: 'Private tour for couples, families, and small groups',
    priceInr: null,
    priceUsd: 1606,
    destinations: ['Hanoi', 'Halong Bay', 'Titov Island'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Short northern Vietnam break',
    locationIdea: 'Hanoi and Halong Bay',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-vietnam-hanoi-halong-saigon',
    title: 'Vietnam north to south',
    slug: 'vietnam-hanoi-halong-ho-chi-minh-6-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'Hanoi, a Halong Bay cruise night, the Cu Chi Tunnels, and a Saigon river dinner.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '7 days / 6 nights',
    groupSize: 'Private tour for couples, families, and small groups',
    priceInr: null,
    priceUsd: 2314,
    destinations: ['Hanoi', 'Halong Bay', 'Ho Chi Minh City', 'Cu Chi'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Both ends of Vietnam',
    locationIdea: 'Northern and southern Vietnam',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-croatia-zagreb-dubrovnik-tirana',
    title: 'Croatia and Albania, Zagreb to Tirana',
    slug: 'croatia-zagreb-dubrovnik-tirana-8-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'Adriatic walled cities, Krka waterfalls, Diocletian\'s Palace, and the Bay of Kotor.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1555990793-da11153b2473?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '9 days / 8 nights',
    groupSize: 'Small group departures and private quotes',
    priceInr: null,
    priceUsd: 2832,
    destinations: ['Zagreb', 'Zadar', 'Krka', 'Split', 'Dubrovnik', 'Kotor', 'Tirana'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Adriatic coast overland',
    locationIdea: 'Croatia, Montenegro, and Albania',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-greece-athens',
    title: 'Athens short break',
    slug: 'greece-athens-3-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'The Acropolis, the New Acropolis Museum, and an optional Saronic islands cruise.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1555993539-1732b0258235?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '4 days / 3 nights',
    groupSize: 'Daily departures, seat-in-coach touring',
    priceInr: null,
    priceUsd: 1171,
    destinations: ['Athens', 'Acropolis', 'Hydra', 'Poros', 'Aegina'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Classical city break',
    locationIdea: 'Athens and the Saronic Gulf',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-baltic-capitals-helsinki',
    title: 'Baltic capitals with Helsinki',
    slug: 'baltic-capitals-helsinki-6-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'Riga, Vilnius and Tallinn old towns, Trakai Castle, and a ferry day to Helsinki.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1518975513267-071132b42e06?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '7 days / 6 nights',
    groupSize: 'Small group departures and private quotes',
    priceInr: null,
    priceUsd: 1906,
    destinations: ['Riga', 'Sigulda', 'Rundale', 'Vilnius', 'Trakai', 'Tallinn', 'Helsinki'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Old towns and castles',
    locationIdea: 'Latvia, Lithuania, Estonia, and Finland',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-montenegro-budva',
    title: 'Montenegro from Budva',
    slug: 'montenegro-budva-4-nights',
    market: 'global',
    category: 'Adventure',
    tagline: 'Bay of Kotor, Durmitor National Park, the Tara canyon, and the cliff-set Ostrog Monastery.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1614122027743-50a9e6e8002f?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '5 days / 4 nights',
    groupSize: 'Seat-in-coach excursions from a single base',
    priceInr: null,
    priceUsd: 1497,
    destinations: ['Budva', 'Kotor', 'Perast', 'Durmitor', 'Tara Canyon', 'Zabljak', 'Ostrog'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Coast base with mountain days',
    locationIdea: 'The Montenegrin coast and Durmitor',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-united-kingdom-london',
    title: 'London short break',
    slug: 'united-kingdom-london-4-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'A guided landmark tour, a Thames cruise, and two free days for Windsor or Harry Potter.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1486299267070-83823f5448dd?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '5 days / 4 nights',
    groupSize: 'Daily departures and private quotes',
    priceInr: null,
    priceUsd: 1497,
    destinations: ['London', 'Westminster', 'Tower Bridge', 'River Thames'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Landmark city break',
    locationIdea: 'Central London',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-nordic-arctic',
    title: 'Nordic Arctic circuit',
    slug: 'nordic-norway-sweden-finland-8-nights',
    market: 'global',
    category: 'Adventure',
    tagline: 'Northern lights, the Ice Hotel, husky and reindeer sleighs, and the Arctic train to Abisko.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '9 days / 8 nights',
    groupSize: 'Small group departures with a tour manager',
    priceInr: null,
    priceUsd: 6070,
    destinations: ['Oslo', 'Tromso', 'Narvik', 'Kiruna', 'Abisko', 'Rovaniemi', 'Helsinki'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Arctic winter expedition',
    locationIdea: 'Norway, Sweden, and Finnish Lapland',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-italy-rome-florence-venice',
    title: 'Italy, Rome to Venice',
    slug: 'italy-rome-florence-venice-6-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'Two nights each in Rome, Florence and Venice, with a Pisa stop between them.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '7 days / 6 nights',
    groupSize: 'Small group departures and private quotes',
    priceInr: null,
    priceUsd: 3104,
    destinations: ['Rome', 'Florence', 'Pisa', 'Venice'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Renaissance city triangle',
    locationIdea: 'Lazio, Tuscany, and the Veneto',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-lisbon-to-madrid',
    title: 'Lisbon to Madrid overland',
    slug: 'portugal-spain-lisbon-to-madrid-7-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'Lisbon, the Templar town of Tomar, Fatima, Porto, Salamanca, and Madrid.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1585208798174-6cedd86e019a?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '8 days / 7 nights',
    groupSize: 'Small group departures and private quotes',
    priceInr: null,
    priceUsd: 3512,
    destinations: ['Lisbon', 'Tomar', 'Fatima', 'Porto', 'Salamanca', 'Madrid'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Iberian overland route',
    locationIdea: 'Portugal and central Spain',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-portugal-grand-tour',
    title: 'Portugal in depth',
    slug: 'portugal-grand-tour-8-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'Lisbon, Nazare and Alcobaca, Coimbra University, Porto, and the walled town of Belmonte.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '9 days / 8 nights',
    groupSize: 'Small group departures and private quotes',
    priceInr: null,
    priceUsd: 3077,
    destinations: ['Lisbon', 'Tomar', 'Nazare', 'Alcobaca', 'Coimbra', 'Porto', 'Viseu', 'Belmonte', 'Evora'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Slow Portugal',
    locationIdea: 'Coastal and inland Portugal',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-paris-amsterdam-switzerland',
    title: 'Paris, Amsterdam and Switzerland',
    slug: 'paris-amsterdam-switzerland-8-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'The Eiffel Tower, Amsterdam canals, and the Swiss Alps on one fixed departure.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '9 days / 8 nights',
    groupSize: 'Fixed departure, small group',
    priceInr: null,
    priceUsd: 2451,
    destinations: ['Paris', 'Amsterdam', 'Zurich', 'Lucerne', 'Interlaken'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Three-country highlights',
    locationIdea: 'France, the Netherlands, and Switzerland',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-scandinavia-five-countries',
    title: 'Scandinavia and the Baltic',
    slug: 'scandinavia-five-countries-9-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'Helsinki, Tallinn, Stockholm, Oslo, the Geilo mountains, and Copenhagen.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1445168580797-f946f0688547?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '10 days / 9 nights',
    groupSize: 'Fixed departure, small group',
    priceInr: null,
    priceUsd: 3267,
    destinations: ['Helsinki', 'Tallinn', 'Stockholm', 'Oslo', 'Geilo', 'Copenhagen'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Nordic capitals circuit',
    locationIdea: 'Finland, Estonia, Sweden, Norway, and Denmark',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-eastern-europe-four-countries',
    title: 'Eastern Europe, Munich to Prague',
    slug: 'eastern-europe-munich-vienna-budapest-prague-9-nights',
    market: 'global',
    category: 'Heritage',
    tagline: 'Bavaria, Salzburg, Vienna, Budapest and Prague across four countries.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '10 days / 9 nights',
    groupSize: 'Fixed departure, small group',
    priceInr: null,
    priceUsd: 2451,
    destinations: ['Munich', 'Salzburg', 'Vienna', 'Budapest', 'Prague'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Four countries by coach',
    locationIdea: 'Germany, Austria, Hungary, and Czechia',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-switzerland-paris-italy',
    title: 'Switzerland, Paris and Italy',
    slug: 'switzerland-paris-italy-11-nights',
    market: 'global',
    category: 'Adventure',
    tagline: 'The Alps, Paris landmarks, and the Italian triangle on one long fixed departure.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1527668752968-14dc70a27c95?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '12 days / 11 nights',
    groupSize: 'Fixed departure, small group',
    priceInr: null,
    priceUsd: 3186,
    destinations: ['Zurich', 'Mount Titlis', 'Lucerne', 'Interlaken', 'Paris', 'Venice', 'Florence', 'Rome'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'The long European run',
    locationIdea: 'Switzerland, France, and Italy',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-germany-metzingen-baden-baden',
    title: 'Metzingen, Baden-Baden and Stuttgart',
    slug: 'germany-metzingen-baden-baden-stuttgart-5-nights',
    market: 'global',
    category: 'Wellness',
    tagline: 'Europe\'s largest outlet city, thermal spa days, and the Black Forest edge.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '6 days / 5 nights',
    groupSize: 'Private quotes for couples, families, and small groups',
    priceInr: null,
    priceUsd: 2478,
    destinations: ['Stuttgart', 'Metzingen', 'Baden-Baden', 'Black Forest'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Shopping and spa days',
    locationIdea: 'Baden-Wurttemberg',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
  {
    id: 'static-global-germany-metzingen-munich-salzburg',
    title: 'Metzingen, Munich and Salzburg',
    slug: 'germany-metzingen-munich-salzburg-5-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'Outlet shopping in Swabia, Bavarian old town days, and a Salzburg excursion.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1595867818082-083862f3d630?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '6 days / 5 nights',
    groupSize: 'Private quotes for couples, families, and small groups',
    priceInr: null,
    priceUsd: 2695,
    destinations: ['Stuttgart', 'Metzingen', 'Munich', 'Salzburg'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Shopping with Bavarian city days',
    locationIdea: 'Swabia, Bavaria, and Salzburg',
    status: 'published',
    createdAt: '2026-07-20T00:00:00.000Z',
  },
];
