import type { Package } from '@/types';

const included = {
  accommodation: false,
  meals: false,
  transfers: false,
  guides: false,
  flights: false,
  activities: false,
};

export const STATIC_GLOBAL_PACKAGE_SUMMARIES: Package[] = [
  {
    id: 'static-global-thailand-pattaya',
    title: 'Pattaya beach break',
    slug: 'pattaya-thailand-3-nights',
    market: 'global',
    category: 'Beach',
    tagline: 'A short Thailand escape with island waters, cabaret lights, and tropical gardens.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '4 days / 3 nights',
    groupSize: 'Private groups from 4 travelers',
    priceInr: 56400,
    priceUsd: 680,
    destinations: ['Bangkok', 'Pattaya', 'Coral Island', 'Nong Nooch'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Easy beach holiday',
    locationIdea: 'Pattaya, Thailand',
    status: 'published',
    createdAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'static-global-vietnam-danang-ho-chi-minh',
    title: 'Da Nang to Ho Chi Minh discovery',
    slug: 'vietnam-da-nang-ho-chi-minh-6-nights',
    market: 'global',
    category: 'Culture',
    tagline: 'Golden Bridge, Hoi An lanterns, Saigon landmarks, and the Cu Chi tunnel network.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '7 days / 6 nights',
    groupSize: 'Private tour for couples, families, and small groups',
    priceInr: null,
    priceUsd: 915,
    destinations: ['Da Nang', 'Ba Na Hills', 'Hoi An', 'Ho Chi Minh City', 'Cu Chi'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Culture, coast, and city',
    locationIdea: 'Central and southern Vietnam',
    status: 'published',
    createdAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'static-global-vietnam-phu-quoc-hanoi-halong',
    title: 'Phu Quoc, Hanoi and Halong Bay',
    slug: 'vietnam-phu-quoc-hanoi-halong-7-nights',
    market: 'global',
    category: 'Beach',
    tagline: 'Island snorkeling, Hanoi old quarter, Halong Bay cruising, and Ninh Binh limestone landscapes.',
    heroImageUrl:
      'https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '8 days / 7 nights',
    groupSize: 'Private and small-group touring blend',
    priceInr: null,
    priceUsd: 650,
    destinations: ['Phu Quoc', 'Hanoi', 'Halong Bay', 'Ninh Binh', 'Trang An'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Island to limestone landscapes',
    locationIdea: 'Southern island and northern Vietnam',
    status: 'published',
    createdAt: '2026-07-10T00:00:00.000Z',
  },
  {
    id: 'static-global-kenya-safari',
    title: 'Kenya safari circuit',
    slug: 'kenya-amboseli-naivasha-masai-mara-9-nights',
    market: 'global',
    category: 'Safari',
    tagline: "Amboseli elephants, Lake Naivasha, Hell's Gate, and extended Masai Mara game drives.",
    heroImageUrl:
      'https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&q=80&w=1600',
    galleryUrls: [],
    duration: '10 days / 9 nights',
    groupSize: 'Private safari quote for small groups',
    priceInr: null,
    priceUsd: 5387,
    destinations: ['Nairobi', 'Amboseli', 'Lake Naivasha', "Hell's Gate", 'Masai Mara'],
    overviewHtml: '',
    itinerary: [],
    inclusions: included,
    exclusions: [],
    vibe: 'Wildlife-forward safari',
    locationIdea: 'Amboseli, Naivasha, and Masai Mara',
    status: 'published',
    createdAt: '2026-07-10T00:00:00.000Z',
  },
];
